import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const initialPosts = [
  // Core Jobs
  {
    title: 'SSC CGL 2026 Notification, Online Form',
    slug: 'ssc-cgl-2026-notification',
    category: 'JOB',
    shortDescription: 'Staff Selection Commission (SSC) has released the Combined Graduate Level (CGL) 2026 notification. Candidates can apply online.',
    content: 'The Staff Selection Commission has released the notification for the Combined Graduate Level Examination, 2026. This exam aims to fill various Group B and Group C posts in different Ministries/Departments/Organizations of the Government of India.\n\n<!-- Search Keywords: ssc, cgl, job, vacancy, bharti, sarkari result, ssc cgl 2026 -->',
    importantDates: '{"Application Start": "10-09-2026", "Last Date": "09-10-2026", "Exam Date Tier 1": "Dec 2026"}',
    eligibility: 'Bachelor Degree in Any Stream from a Recognized University in India.',
    applicationProcess: '1. Visit the official SSC website. 2. Register/Login. 3. Fill the CGL 2026 application form. 4. Upload photo/signature. 5. Pay the fee and submit.',
    requiredDocuments: 'Aadhar Card, 10th/12th/Graduation Marksheets, Photo, Signature.',
    officialSourceUrl: 'https://ssc.nic.in/',
    published: true,
  },
  {
    title: 'UP Police Constable Recruitment 2026',
    slug: 'up-police-constable-recruitment-2026',
    category: 'JOB',
    shortDescription: 'Uttar Pradesh Police Recruitment and Promotion Board (UPPRPB) invites applications for 35,000+ Constable posts.',
    content: 'UP Police has announced a massive recruitment drive for Constables. Interested and eligible candidates can apply online.\n\n<!-- Search Keywords: up police, constable, police bharti, job, vacancy -->',
    importantDates: '{"Application Start": "15-09-2026", "Last Date": "15-10-2026"}',
    eligibility: '10+2 (Intermediate) Exam Passed in Any Recognized Board in India.',
    applicationProcess: 'Apply online through the UPPRPB official portal.',
    requiredDocuments: 'Aadhar Card, 10th/12th Marksheets, Domicile Certificate, Caste Certificate, Photo, Signature.',
    officialSourceUrl: 'https://uppbpb.gov.in/',
    published: true,
  },
  // Core Results
  {
    title: 'IBPS PO Mains Result 2026 Declared',
    slug: 'ibps-po-mains-result-2026',
    category: 'RESULT',
    shortDescription: 'Institute of Banking Personnel Selection (IBPS) has declared the Mains Result for Probationary Officer (PO) recruitment.',
    content: 'Candidates who appeared for the IBPS PO Mains examination can now check their results and scorecard on the official website.\n\n<!-- Search Keywords: ibps, po, result, bank po result, score card -->',
    importantDates: '{"Mains Exam Date": "Aug 2026", "Result Declared": "05-09-2026"}',
    applicationProcess: 'Login with Registration No / Roll No and Password / DOB to view the result.',
    officialSourceUrl: 'https://ibps.in/',
    published: true,
  },
  // Core Admit Cards
  {
    title: 'UPSC Civil Services Mains Admit Card 2026',
    slug: 'upsc-civil-services-mains-admit-card-2026',
    category: 'ADMIT_CARD',
    shortDescription: 'Union Public Service Commission (UPSC) has released the admit cards for the Civil Services Mains Examination 2026.',
    content: 'Candidates who have cleared the preliminary exam can download their admit card for the mains examination from the UPSC official website.\n\n<!-- Search Keywords: upsc, ias, admit card, hall ticket, mains admit card -->',
    importantDates: '{"Admit Card Release": "01-09-2026", "Mains Exam Date": "20-09-2026 to 29-09-2026"}',
    requiredDocuments: 'Admit Card Printout, Original Photo ID Card.',
    officialSourceUrl: 'https://upsc.gov.in/',
    published: true,
  },
  // PAN Card with direct application link
  {
    title: 'पैनकार्ड (PAN Card Online Apply & Correction)',
    slug: 'pan-card-online-apply',
    category: 'SARKARI_KAAM',
    shortDescription: 'नया पैन कार्ड ऑनलाइन बनाएं या पुराने पैन कार्ड में सुधार करें। NSDL/UTIITSL आधिकारिक पोर्टल।',
    content: 'यहाँ से आप नए पैन कार्ड के लिए ऑनलाइन आवेदन कर सकते हैं या पुराने पैन कार्ड में सुधार कर सकते हैं। आवेदन करने के लिए नीचे दिए गए "Visit Official Website" बटन पर क्लिक करें।\n\nजरूरी दस्तावेज़: आधार कार्ड, पासपोर्ट साइज फोटो और सिग्नेचर।\n\n<!-- Search Keywords: pan, pancard, pan card, nsdl, uti, apply pan card online, download e-pan -->',
    eligibility: 'भारतीय नागरिक (नाबालिग एवं बालिग दोनों आवेदन कर सकते हैं)',
    applicationProcess: '1. NSDL/UTIITSL पोर्टल खोलें। 2. Form 49A चुनें। 3. विवरण भरें और आधार e-KYC करें। 4. ऑनलाइन शुल्क का भुगतान करें।',
    requiredDocuments: 'आधार कार्ड (पहचान व पते का प्रमाण), 2 पासपोर्ट साइज फोटो।',
    officialSourceUrl: 'https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html',
    published: true,
  },
  // Yojanas & Government Schemes
  {
    title: 'पीएम किसान सम्मान निधि योजना (PM Kisan 18th Installment)',
    slug: 'pm-kisan-samman-nidhi-yojana-18th-installment',
    category: 'YOJANA',
    shortDescription: 'Check status for the 18th installment of PM Kisan Samman Nidhi Yojana. Eligible farmers get ₹6,000 per year.',
    content: 'प्रधानमंत्री किसान सम्मान निधि योजना के तहत पात्र किसानों को सालाना 6000 रुपये 3 किश्तों में दिए जाते हैं। e-KYC अनिवार्य है।\n\n<!-- Search Keywords: pm kisan, kisan, farmer, 18th installment, kisan samman nidhi -->',
    eligibility: 'छोटे और सीमांत किसान परिवार जिनके पास खेती योग्य जमीन है।',
    applicationProcess: 'आधिकारिक पीएम किसान पोर्टल पर जाएं या नजदीकी CSC केंद्र से आवेदन करें।',
    officialSourceUrl: 'https://pmkisan.gov.in/',
    published: true,
  },
  {
    title: 'गर्भवती महिला को रु 11000 की सहायता NEW',
    slug: 'garbhvati-mahila-11000-sahayata',
    category: 'YOJANA',
    shortDescription: 'गर्भवती महिलाओं के लिए 11000 रुपये की आर्थिक सहायता योजना।',
    content: 'गर्भवती एवं धात्री माताओं के पोषण एवं स्वास्थ्य देखभाल हेतु सरकार द्वारा आर्थिक सहायता प्रदान की जाती है।\n\n<!-- Search Keywords: pregnant, pregnancy, maternity, mahila, women, yojana, 11000 -->',
    officialSourceUrl: 'https://wcd.nic.in/',
    published: true,
  },
  {
    title: 'महिलाओं को हर महीने 2,500 रुपये NEW',
    slug: 'mahila-2500-rupees-monthly',
    category: 'YOJANA',
    shortDescription: 'महिलाओं के लिए प्रतिमाह 2500 रुपये की आर्थिक सहायता योजना।',
    content: 'राज्य सरकार द्वारा महिलाओं को आत्मनिर्भर बनाने हेतु हर महीने 2500 रुपये की सहायता राशि सीधे बैंक खाते में भेजी जाती है।\n\n<!-- Search Keywords: mahila, women, 2500, monthly pension, yojana -->',
    officialSourceUrl: 'https://india.gov.in',
    published: true,
  },
  {
    title: 'दिल्ली लक्ष्मी योजना (2,500 रुपये ) NEW',
    slug: 'delhi-lakshmi-yojana-2500',
    category: 'YOJANA',
    shortDescription: 'दिल्ली सरकार द्वारा लक्ष्मी योजना के तहत महिलाओं को 2500 रुपये प्रतिमाह सहायता।',
    content: 'दिल्ली सरकार की इस योजना के तहत पात्र महिलाओं को वित्तीय स्वतंत्रता हेतु मासिक आर्थिक मदद दी जाती है।\n\n<!-- Search Keywords: delhi lakshmi yojana, delhi scheme, women 2500, mahila -->',
    officialSourceUrl: 'https://delhi.gov.in',
    published: true,
  },
  {
    title: 'बेटी को जन्म से रु 25000',
    slug: 'beti-janm-25000-sahayata',
    category: 'YOJANA',
    shortDescription: 'बेटी के जन्म पर 25000 रुपये की आर्थिक सहायता योजना।',
    content: 'बालिकाओं के जन्म को प्रोत्साहित करने और उनके पालन-पोषण में सहायता हेतु वित्तीय प्रोत्साहन राशि।\n\n<!-- Search Keywords: beti, girl, kanya, birth, 25000, yojana -->',
    officialSourceUrl: 'https://india.gov.in',
    published: true,
  },
  {
    title: 'युवा के लिए 9000 हर महीने',
    slug: 'yuva-9000-monthly-stipend',
    category: 'YOJANA',
    shortDescription: 'युवाओं के लिए 9000 रुपये प्रतिमाह सीखो कमाओ / अप्रेंटिसशिप योजना।',
    content: 'युवाओं को कौशल विकास प्रशिक्षण के साथ प्रति माह ₹8000 से ₹9000 तक का मानदेय उपलब्ध कराया जाता है।\n\n<!-- Search Keywords: yuva, youth, 9000, berojgar, internship, stipend -->',
    officialSourceUrl: 'https://india.gov.in',
    published: true,
  },
  {
    title: 'वर्क फ्रॉम होम जॉब (Work From Home Opportunities)',
    slug: 'work-from-home-jobs',
    category: 'JOB',
    shortDescription: 'घर बैठे काम करने के आधिकारिक अवसर एवं सरकारी पोर्टल आधारित नौकरियां।',
    content: 'National Career Service (NCS) पोर्टल पर घर बैठे काम करने के सत्यापित अवसर उपलब्ध हैं।\n\n<!-- Search Keywords: work from home, wfh, job, vacancy, ncs -->',
    officialSourceUrl: 'https://www.ncs.gov.in/',
    published: true,
  },
  {
    title: 'लाड़ली लक्ष्मी योजना',
    slug: 'ladli-lakshmi-yojana',
    category: 'YOJANA',
    shortDescription: 'मध्य प्रदेश लाड़ली लक्ष्मी योजना - बेटियों के भविष्य और उच्च शिक्षा के लिए।',
    content: 'बालिकाओं के भविष्य को संवारने एवं उच्च शिक्षा तक आर्थिक सुरक्षा देने के लिए शुरू की गई प्रमुख योजना।\n\n<!-- Search Keywords: ladli lakshmi, mp yojana, beti, girl, scholarship -->',
    officialSourceUrl: 'https://ladlilaxmi.mp.gov.in/',
    published: true,
  },
  {
    title: 'जनगणना 2026 (Census India Updates)',
    slug: 'census-2026-updates',
    category: 'NEWS',
    shortDescription: 'भारत की जनगणना 2026 से सम्बंधित महत्वपूर्ण जानकारी और आधिकारिक अपडेट।',
    content: 'आगामी डिजिटल जनगणना प्रक्रिया और नागरिकों से जुड़े प्रमुख दिशा-निर्देश।\n\n<!-- Search Keywords: census, janganana, news, update -->',
    officialSourceUrl: 'https://censusindia.gov.in/',
    published: true,
  },
  {
    title: 'PF अकाउंट वालो को मिलेगा नया लाभ (EPFO Updates)',
    slug: 'epfo-pf-account-benefits',
    category: 'YOJANA',
    shortDescription: 'PF अकाउंट धारकों के लिए नया ब्याज दर और बीमा लाभ।',
    content: 'EPFO द्वारा ईपीएस पेंशन और EDLI जीवन बीमा के तहत मिलने वाले लाभों की विस्तृत जानकारी।\n\n<!-- Search Keywords: pf, epfo, provident fund, passbook, claim -->',
    officialSourceUrl: 'https://www.epfindia.gov.in/',
    published: true,
  },
  {
    title: 'बेरोजगार युवा को 1000 रूपये हर महीने (बेरोजगारी भत्ता)',
    slug: 'berojgar-yuva-1000-bhatta',
    category: 'YOJANA',
    shortDescription: 'बेरोजगारी भत्ता योजना के तहत शिक्षित बेरोजगार युवाओं को हर महीने 1000 रुपये।',
    content: 'रोजगार की तलाश कर रहे युवाओं को आर्थिक संबल प्रदान करने हेतु मासिक भत्ता योजना।\n\n<!-- Search Keywords: berojgar, bhatta, youth, unemployed, 1000 -->',
    officialSourceUrl: 'https://india.gov.in',
    published: true,
  },
  {
    title: 'रोजगार के लिए 10 लाख तक लोन (PMEGP / Mudra Loan)',
    slug: 'mudra-loan-10-lakh',
    category: 'YOJANA',
    shortDescription: 'स्वरोजगार शुरू करने के लिए सरकार द्वारा 10 लाख रुपये तक का आसान लोन।',
    content: 'प्रधानमंत्री मुद्रा योजना एवं PMEGP के तहत नए व्यापार हेतु सब्सिडी और ऋण सुविधा।\n\n<!-- Search Keywords: loan, mudra, pmegp, business loan, credit -->',
    officialSourceUrl: 'https://www.mudra.org.in/',
    published: true,
  },
  {
    title: 'फॉर्मर रजिस्ट्री (Farmer Registry Portal)',
    slug: 'farmer-registry-portal',
    category: 'SARKARI_KAAM',
    shortDescription: 'किसानों के लिए फॉर्मर रजिस्ट्री में पंजीकरण और डिजिटल किसान आईडी निर्माण।',
    content: 'किसान आईडी बनाने और सरकारी योजनाओं का सीधा लाभ पाने के लिए फॉर्मर रजिस्ट्री में विवरण दर्ज करें।\n\n<!-- Search Keywords: farmer registry, kisan, farmer id, agriculture -->',
    officialSourceUrl: 'https://agristack.gov.in/',
    published: true,
  },
  {
    title: 'पीएम विद्यालक्ष्मी लोन (10 लाख रुपये तक शिक्षा ऋण)',
    slug: 'pm-vidyalakshmi-education-loan',
    category: 'YOJANA',
    shortDescription: 'छात्रों की उच्च शिक्षा के लिए बिना गारंटी 10 लाख तक पीएम विद्यालक्ष्मी लोन।',
    content: 'देश के शीर्ष उच्च शिक्षण संस्थानों में प्रवेश लेने वाले छात्रों के लिए ब्याज छूट के साथ शिक्षा ऋण।\n\n<!-- Search Keywords: vidyalakshmi, education loan, student loan, scholarship -->',
    officialSourceUrl: 'https://www.vidyalakshmi.co.in/',
    published: true,
  },
  {
    title: 'विधवा महिला को रु. 30000 की सहायता (विधवा पेंशन व संबल)',
    slug: 'vidhwa-pension-sahayata',
    category: 'YOJANA',
    shortDescription: 'निराश्रित एवं विधवा महिलाओं के लिए आर्थिक सुरक्षा योजना।',
    content: 'विधवा महिलाओं को भरण-पोषण एवं सामाजिक सुरक्षा प्रदान करने हेतु पेंशन योजना।\n\n<!-- Search Keywords: vidhwa, widow, pension, mahila, 30000 -->',
    officialSourceUrl: 'https://india.gov.in',
    published: true,
  },
  {
    title: 'पक्का मकान के लिए 2.5 लाख (PM Awas Yojana)',
    slug: 'pm-awas-yojana-2-point-5-lakh',
    category: 'YOJANA',
    shortDescription: 'प्रधानमंत्री आवास योजना के तहत पक्का मकान बनाने के लिए ₹2.5 लाख तक अनुदान।',
    content: 'बेघर एवं कच्चे मकानों में रहने वाले परिवारों को पक्का मकान निर्माण हेतु सीधी सब्सिडी राशि।\n\n<!-- Search Keywords: awas, makan, house, pm awas, home loan -->',
    officialSourceUrl: 'https://pmaymis.gov.in/',
    published: true,
  },
  {
    title: 'लेबर पंजीयन 7000 रु (श्रम विभाग श्रमिक कार्ड)',
    slug: 'labour-card-registration-7000',
    category: 'SARKARI_KAAM',
    shortDescription: 'श्रमिकों के लेबर कार्ड पंजीयन पर विभिन्न योजनाओं के तहत 7000 रुपये तक सहायता।',
    content: 'भवन निर्माण एवं असंगठित मजदूरों को चिकित्सा, छात्रवृत्ति और विवाह सहायता हेतु श्रमिक कार्ड पंजीयन।\n\n<!-- Search Keywords: labour, labor, shramik, majdoor, labour card -->',
    officialSourceUrl: 'https://eshram.gov.in/',
    published: true,
  },
  {
    title: 'राशन कार्ड डाउनलोड (NFSA Digital Ration Card)',
    slug: 'ration-card-download-online',
    category: 'SARKARI_KAAM',
    shortDescription: 'अपना नया या पुराना डिजिटल राशन कार्ड ऑनलाइन डाउनलोड करें।',
    content: 'राष्ट्रीय खाद्य सुरक्षा पोर्टल (NFSA) से अपने परिवार का डिजिटल राशन कार्ड डाउनलोड करें और राशन कोटा देखें।\n\n<!-- Search Keywords: ration, ration card, rasan, nfsa, khadya -->',
    officialSourceUrl: 'https://nfsa.gov.in/',
    published: true,
  },
  {
    title: 'कन्या उत्थान योजना (बेटी को आगे पढ़ने के लिए 25000 की सहायता)',
    slug: 'kanya-utthan-yojana-25000',
    category: 'YOJANA',
    shortDescription: 'मुख्यमंत्री कन्या उत्थान योजना के तहत स्नातक पास बेटियों को ₹25,000 से ₹50,000 की प्रोत्साहन राशि।',
    content: 'छात्राओं को उच्च शिक्षा की ओर प्रेरित करने हेतु स्नातक उत्तीर्ण होने पर सीधी छात्रवृत्ति।\n\n<!-- Search Keywords: kanya utthan, beti, girl scholarship, 25000 -->',
    officialSourceUrl: 'https://medhasoft.bih.nic.in/',
    published: true,
  },
  {
    title: 'LIC बिमा सखी भर्ती (महिला स्वरोजगार)',
    slug: 'lic-bima-sakhi-yojana',
    category: 'JOB',
    shortDescription: 'महिलाओं के लिए भारतीय जीवन बीमा निगम (LIC) में बीमा सखी बनकर कमाने का सुनहरा अवसर।',
    content: 'महिलाएं घर के कामकाज के साथ बीमा सखी के रूप में नियमित आय प्राप्त कर सकती हैं।\n\n<!-- Search Keywords: lic, bima sakhi, job, women, insurance agent -->',
    officialSourceUrl: 'https://licindia.in/',
    published: true,
  },
  {
    title: 'LPG Gas eKYC ऑनलाइन करें',
    slug: 'lpg-gas-ekyc-online',
    category: 'SARKARI_KAAM',
    shortDescription: 'अपने Indane, HP, Bharat Gas कनेक्शन की eKYC ऑनलाइन पूरी करें ताकि सब्सिडी चालू रहे।',
    content: 'बिना एजेंसी गए घर बैठे मोबाइल ऐप या आधिकारिक वेबसाइट से आधार फेस आरडी के जरिए बायोमेट्रिक eKYC करें।\n\n<!-- Search Keywords: gas, lpg, ekyc, indane, hp, bharat gas, subsidy -->',
    officialSourceUrl: 'https://myhpgas.in/',
    published: true,
  },
  {
    title: 'बेटी की शादी के लिए 1 लाख (विवाह अनुदान योजना)',
    slug: 'shadi-anudan-yojana-1-lakh',
    category: 'YOJANA',
    shortDescription: 'गरीब परिवारों की बेटियों के विवाह हेतु सरकारी अनुदान योजना।',
    content: 'गरीबी रेखा से नीचे जीवन यापन करने वाले परिवारों की कन्याओं के विवाह हेतु आर्थिक मदद।\n\n<!-- Search Keywords: shadi, vivah, marriage, beti, anudan, 1 lakh -->',
    officialSourceUrl: 'https://shadianudan.upsdc.gov.in/',
    published: true,
  },
  {
    title: 'बैंक से आधार लिंक करे (NPCI DBT Status)',
    slug: 'bank-aadhar-link-npci',
    category: 'SARKARI_KAAM',
    shortDescription: 'डीबीटी योजनाओं का पैसा पाने के लिए अपने बैंक खाते में NPCI आधार मैपिंग चेक और लिंक करें।',
    content: 'सरकारी सब्सिडी और छात्रवृत्ति सीधे खाते में पाने हेतु बैंक खाते को NPCI आधार ब्रिज से जोड़ना अनिवार्य है।\n\n<!-- Search Keywords: aadhar, npci, dbt, bank link, uidai -->',
    officialSourceUrl: 'https://myaadhaar.uidai.gov.in/',
    published: true,
  },
  // Scholarships
  {
    title: 'छात्रों को रु 50000 तक स्कॉलरशिप (National Scholarship Portal)',
    slug: 'nsp-scholarship-50000',
    category: 'SCHOLARSHIP',
    shortDescription: 'कक्षा 12वीं एवं कॉलेज के मेधावी छात्रों के लिए 50000 रुपये तक की नेशनल स्कॉलरशिप।',
    content: 'केन्द्र सरकार के विभिन्न मंत्रालयों द्वारा मेधावी विद्यार्थियों के लिए छात्रवृत्ति पोर्टल पर आवेदन आमंत्रित।\n\n<!-- Search Keywords: scholarship, nsp, student, 50000 -->',
    officialSourceUrl: 'https://scholarships.gov.in/',
    published: true,
  },
  {
    title: 'SBI आशा स्कॉलरशिप (₹15,000 से लेकर ₹15 लाख तक छात्रवृत्ति)',
    slug: 'sbi-asha-scholarship',
    category: 'SCHOLARSHIP',
    shortDescription: 'कक्षा 9वीं से 12वीं, स्नातक, स्नातकोत्तर, MBBS, IIT, IIM के छात्रों के लिए SBI आशा स्कॉलरशिप।',
    content: 'SBI फाउंडेशन द्वारा आर्थिक रूप से कमजोर परिवारों के मेधावी छात्रों की संपूर्ण शिक्षा हेतु छात्रवृत्ति।\n\n<!-- Search Keywords: sbi asha scholarship, scholarship, sbi, mbbs, iit, iim -->',
    officialSourceUrl: 'https://www.sbifoundation.in/',
    published: true,
  },
  {
    title: 'अजीम प्रेमजी स्कॉलरशिप (₹30,000 छात्रवृत्ति मेधावी छात्राओं को)',
    slug: 'azim-premji-scholarship',
    category: 'SCHOLARSHIP',
    shortDescription: 'डिप्लोमा एवं स्नातक की पढ़ाई करने वाली छात्राओं के लिए अजीम प्रेमजी फाउंडेशन की छात्रवृत्ति।',
    content: 'अजीम प्रेमजी फिलैंथ्रोपिक इनिशिएटिव द्वारा बालिकाओं की उच्च शिक्षा में सहायता हेतु स्कॉलरशिप।\n\n<!-- Search Keywords: azim premji scholarship, scholarship, girl student -->',
    officialSourceUrl: 'https://www.azimpremjifoundation.org/',
    published: true,
  },
  {
    title: 'रिलायंस फाउंडेशन स्कॉलरशिप (₹60,000 तक का अनुदान)',
    slug: 'reliance-foundation-scholarship',
    category: 'SCHOLARSHIP',
    shortDescription: 'अंडरग्रेजुएट प्रथम वर्ष के छात्रों के लिए रिलायंस फाउंडेशन स्कॉलरशिप योजना।',
    content: 'मेधावी विद्यार्थियों को उनकी उच्च शिक्षा की अवधि के दौरान ₹2 लाख से ₹6 लाख तक वित्तीय सहयोग।\n\n<!-- Search Keywords: reliance scholarship, scholarship, undergraduate -->',
    officialSourceUrl: 'https://www.reliancefoundation.org/',
    published: true,
  },
  // Essential Citizen Services
  {
    title: 'पासपोर्ट सेवा ऑनलाइन पोर्टल (Passport Seva)',
    slug: 'passport-seva-online-portal',
    category: 'SARKARI_KAAM',
    shortDescription: 'नया पासपोर्ट बनवाने, रिन्यू करने या अपॉइंटमेंट बुक करने के लिए ऑनलाइन आवेदन करें।',
    content: 'विदेश मंत्रालय भारत सरकार का आधिकारिक पासपोर्ट आवेदन एवं ट्रैकिंग पोर्टल।\n\n<!-- Search Keywords: passport, passport seva, online apply passport -->',
    officialSourceUrl: 'https://www.passportindia.gov.in/',
    published: true,
  },
  {
    title: 'भूलेख और भू नक्शा (अपनी ज़मीन का खसरा-खतौनी व नक्शा देखें)',
    slug: 'bhulekh-bhu-naksha-online',
    category: 'SARKARI_KAAM',
    shortDescription: 'अपनी ज़मीन का खसरा, खतौनी, भूलेख और डिजिटल नक्शा ऑनलाइन चेक व डाउनलोड करें।',
    content: 'राजस्व विभाग के भूलेख पोर्टल पर अपने जिले, तहसील और गांव का चयन करके जमीन का विवरण देखें।\n\n<!-- Search Keywords: bhulekh, bhu naksha, land, record, khatauni, jameen, map -->',
    officialSourceUrl: 'https://upbhulekh.gov.in/',
    published: true,
  },
  {
    title: 'ई-श्रम कार्ड (e-Shram Card Registration & Download)',
    slug: 'e-shram-card-registration',
    category: 'SARKARI_KAAM',
    shortDescription: 'असंगठित क्षेत्र के कामगारों के लिए ई-श्रम कार्ड ऑनलाइन बनाएं और डाउनलोड करें।',
    content: 'ई-श्रम पोर्टल पर पंजीकरण करने पर ₹2 लाख का दुर्घटना बीमा एवं सरकारी योजनाओं का सीधा लाभ मिलता है।\n\n<!-- Search Keywords: eshram, e-shram, shram card, labour -->',
    officialSourceUrl: 'https://eshram.gov.in/',
    published: true,
  },
  {
    title: 'आयुष्मान भारत कार्ड (Ayushman Golden Card - 5 लाख का मुफ्त इलाज)',
    slug: 'ayushman-card-apply-download',
    category: 'SARKARI_KAAM',
    shortDescription: 'प्रति परिवार प्रति वर्ष 5 लाख रुपये तक के मुफ्त इलाज के लिए आयुष्मान कार्ड डाउनलोड करें।',
    content: 'प्रधानमंत्री जन आरोग्य योजना (PMJAY) के तहत सूचीबद्ध अस्पतालों में कैशलेस इलाज की सुविधा।\n\n<!-- Search Keywords: ayushman, ayusman, health card, pmjay, 5 lakh -->',
    officialSourceUrl: 'https://beneficiary.nha.gov.in/',
    published: true,
  },
  {
    title: 'आभा कार्ड (ABHA ID - Ayushman Bharat Health Account)',
    slug: 'abha-card-digital-health-id',
    category: 'SARKARI_KAAM',
    shortDescription: 'डिजिटल हेल्थ रिकॉर्ड सुरक्षित रखने के लिए अपना 14 अंकों का आभा कार्ड बनाएं।',
    content: 'डिजिटल हेल्थ मिशन के अंतर्गत अपने सभी मेडिकल पर्चे और जांच रिपोर्ट एक जगह लिंक करने के लिए डिजिटल हेल्थ अकाउंट।\n\n<!-- Search Keywords: abha, health id, digital health, ayushman -->',
    officialSourceUrl: 'https://abha.abdm.gov.in/',
    published: true,
  },
  {
    title: 'APAAR ID कार्ड (One Nation One Student ID)',
    slug: 'apaar-id-card-student',
    category: 'SARKARI_KAAM',
    shortDescription: 'सभी स्कूली व कॉलेज छात्रों के लिए डिजिटल एकेडमिक आईडी (APAAR ID) कार्ड बनाएं।',
    content: 'नई शिक्षा नीति के तहत छात्रों के सभी प्रमाणपत्र, डिग्री और अंकतालिकाएं डिजिटल रूप से सुरक्षित रखने हेतु।\n\n<!-- Search Keywords: apaar id, student id, abc id, digilocker -->',
    officialSourceUrl: 'https://apaar.education.gov.in/',
    published: true,
  },
  {
    title: 'चोरी या खोया हुआ मोबाइल ब्लॉक और अनब्लॉक करें (CEIR Portal)',
    slug: 'ceir-mobile-block-unblock',
    category: 'SARKARI_KAAM',
    shortDescription: 'संचार साथी (CEIR) पोर्टल के माध्यम से चोरी हुआ मोबाइल फोन ब्लॉक करें और मिलने पर अनब्लॉक करें।',
    content: 'दूरसंचार विभाग के CEIR पोर्टल पर IMEI नंबर डालकर खोए हुए फोन को देश भर में निष्क्रिय कराएं।\n\n<!-- Search Keywords: chori, stolen, lost mobile, ceir, sanchar saathi, block phone -->',
    officialSourceUrl: 'https://www.ceir.gov.in/',
    published: true,
  },
  {
    title: 'आपके नाम पर कितने सिम एक्टिव हैं? (TAFCOP Portal)',
    slug: 'tafcop-check-sim-connections',
    category: 'SARKARI_KAAM',
    shortDescription: 'TAFCOP पोर्टल से तुरंत जानें आपके आधार कार्ड पर कितने मोबाइल नंबर जारी हैं।',
    content: 'यदि कोई अनधिकृत नंबर आपके नाम पर चल रहा है, तो उसे इसी पोर्टल से तुरंत रिपोर्ट व बंद करवा सकते हैं।\n\n<!-- Search Keywords: tafcop, sim, check sim, aadhar sim, mobile number -->',
    officialSourceUrl: 'https://tafcop.sancharsaathi.gov.in/',
    published: true,
  },
  {
    title: 'SIR 2026 Draft Voter List (नयी मतदाता सूची डाउनलोड करें)',
    slug: 'sir-2026-draft-voter-list',
    category: 'SARKARI_KAAM',
    shortDescription: 'भारत निर्वाचन आयोग की नयी वोटर लिस्ट डाउनलोड करें और मतदाता सूची में अपना नाम खोजें।',
    content: 'निर्वाचन आयोग के Voters Services Portal से अपने बूथ की पीडीएफ वोटर लिस्ट डाउनलोड करें।\n\n<!-- Search Keywords: voter, voter list, election, pehchan patra, sir 2026 -->',
    officialSourceUrl: 'https://voters.eci.gov.in/',
    published: true,
  },
];

async function main() {
  console.log('Seeding admin and portal posts...');

  // Create default Admin
  await prisma.user.upsert({
    where: { username: 'admin' },
    update: {},
    create: {
      username: 'admin',
      passwordHash: 'hashed_password_demo',
      role: 'ADMIN',
    },
  });

  // Insert or update all posts
  for (const item of initialPosts) {
    await prisma.post.upsert({
      where: { slug: item.slug },
      update: {
        title: item.title,
        category: item.category,
        shortDescription: item.shortDescription,
        content: item.content,
        importantDates: item.importantDates || null,
        eligibility: item.eligibility || null,
        applicationProcess: item.applicationProcess || null,
        requiredDocuments: item.requiredDocuments || null,
        officialSourceUrl: item.officialSourceUrl || null,
        published: item.published,
      },
      create: {
        title: item.title,
        slug: item.slug,
        category: item.category,
        shortDescription: item.shortDescription,
        content: item.content,
        importantDates: item.importantDates || null,
        eligibility: item.eligibility || null,
        applicationProcess: item.applicationProcess || null,
        requiredDocuments: item.requiredDocuments || null,
        officialSourceUrl: item.officialSourceUrl || null,
        published: item.published,
        publishedAt: new Date(),
      },
    });
  }

  console.log(`Successfully seeded ${initialPosts.length} posts!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
